title: راهنمای جامع مهندسی پرامپت
description: براساس کتاب prompt engineering - google
url: https://aysannazarmohamady.github.io
baseurl: /prompt-engineering-guide

# تم زیبا
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# تنظیمات فارسی
kramdown:
  auto_ids: true
  
# جستجو
search_enabled: true
search:
  heading_level: 2
  previews: 3

# فوتر
footer_content: "ساخته شده با ❤️ برای فارسی‌زبان"

