title: راهنمای جامع مهندسی پرامپت
description: آموزش کامل مهندسی پرامپت به فارسی
baseurl: /prompt-engineering-guide
url: https://aysannazarmohamady.github.io

# تم ساده که حتماً کار می‌کنه
theme: minima

# تنظیمات
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

# تنظیمات اضافی
show_excerpts: true
